batch:
  BatchJobDefinition: 'job_run:1'
  BatchJobName: 'test'
  BatchJobQueue: 'test'

train:
  train_url: <your training image url> 
  data_path: <s3://your/bucket/path>
  hyper_parameter:
    batch_size: 64
    epoch: 1