batch:
  BatchJobDefinition: 'job_run:1'
  BatchJobName: 'test'
  BatchJobQueue: 'test'

train:
  train_url:  <account id>.dkr.ecr.<region>.amazonaws.com/sm-tf-nightly-gpu:latest'
  data_path: 's3://<bucket name>/data'
  hyper_parameter:
    batch_size: 64
    epoch: 1