---
RecipeFormatVersion: '2020-01-25'
ComponentName: com.example.ggmlcomponent
ComponentVersion: '1.0.0'
ComponentPublisher: Amazon
ComponentDependencies:
  aws.greengrass.DockerApplicationManager:
    VersionRequirement: ~2.0.0
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ~2.0.0
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        'com.example.ggmlcomponent:dockerimage:1':
          operations:
            - 'aws.greengrass#PublishToIoTCore'
          resources:
            - 'mlops/inference/result'
Manifests:
  - Platform:
      os: all
    Lifecycle:
      Run: "docker run 222136011322.dkr.ecr.region.amazonaws.com/base.com.example.ggmlcomponent:latest"
    Artifacts:
      - URI: docker:222136011322.dkr.ecr.region.amazonaws.com/base.com.example.ggmlcomponent:latest